### ISSUE TITLE
Is this app still supported?

### ISSUE THREAD

**Issue by iMarang** [komrad36/KPS#2]
Hi,

I'm interested in how I could use KPS to model a CubeSat with a camera on it so I can ultimately derive potential data storage requirements for ongoing data collection.  

I want to test KPS, however, when I've downloaded and extracted the repo I've found a few issues:

* there is no KPS.exe (I can try compiling, but I want to check it before I invest too much time)
* the KPS config.kps run fails

~\Documents\KPS-master>KPS config.kps
'KPS' is not recognized as an internal or external command,
operable program or batch file.

Can you advise?  Ultimately I'll probably need to compile it as I'll potentially want to modify it, but it'd be good to know if this is supported and what's happening with the above first.

Cheers
Ian

**Comment by komrad36** [comment]
Hi Ian,

I have pushed a compiled binary - sorry about that!

I'm around for questions, and KPS is open source and well-documented, via inline comments, the readme, and the KPS thesis (KPS.pdf), so hopefully it proves useful, either directly or as a starting point!

Please feel free to reach out with any other issues or questions!

-Kareem
